// Fonts setup
WebFontConfig={google:{families:['Droid+Sans::latin','Droid+Serif::latin']}};(function(){var wf=document.createElement('script');wf.src=('https:'==document.location.protocol?'https':'http')+'://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';wf.type='text/javascript';wf.async='true';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(wf,s)})();

//  jQuery.ScrollTo - Easy element scrolling using jQuery. //
 ;(function(d){var k=d.scrollTo=function(a,i,e){d(window).scrollTo(a,i,e)};k.defaults={axis:'xy',duration:parseFloat(d.fn.jquery)>=1.3?0:1};k.window=function(a){return d(window)._scrollable()};d.fn._scrollable=function(){return this.map(function(){var a=this,i=!a.nodeName||d.inArray(a.nodeName.toLowerCase(),['iframe','#document','html','body'])!=-1;if(!i)return a;var e=(a.contentWindow||a).document||a.ownerDocument||a;return d.browser.safari||e.compatMode=='BackCompat'?e.body:e.documentElement})};d.fn.scrollTo=function(n,j,b){if(typeof j=='object'){b=j;j=0}if(typeof b=='function')b={onAfter:b};if(n=='max')n=9e9;b=d.extend({},k.defaults,b);j=j||b.speed||b.duration;b.queue=b.queue&&b.axis.length>1;if(b.queue)j/=2;b.offset=p(b.offset);b.over=p(b.over);return this._scrollable().each(function(){var q=this,r=d(q),f=n,s,g={},u=r.is('html,body');switch(typeof f){case'number':case'string':if(/^([+-]=)?\d+(\.\d+)?(px|%)?$/.test(f)){f=p(f);break}f=d(f,this);case'object':if(f.is||f.style)s=(f=d(f)).offset()}d.each(b.axis.split(''),function(a,i){var e=i=='x'?'Left':'Top',h=e.toLowerCase(),c='scroll'+e,l=q[c],m=k.max(q,i);if(s){g[c]=s[h]+(u?0:l-r.offset()[h]);if(b.margin){g[c]-=parseInt(f.css('margin'+e))||0;g[c]-=parseInt(f.css('border'+e+'Width'))||0}g[c]+=b.offset[h]||0;if(b.over[h])g[c]+=f[i=='x'?'width':'height']()*b.over[h]}else{var o=f[h];g[c]=o.slice&&o.slice(-1)=='%'?parseFloat(o)/100*m:o}if(/^\d+$/.test(g[c]))g[c]=g[c]<=0?0:Math.min(g[c],m);if(!a&&b.queue){if(l!=g[c])t(b.onAfterFirst);delete g[c]}});t(b.onAfter);function t(a){r.animate(g,j,b.easing,a&&function(){a.call(this,n,b)})}}).end()};k.max=function(a,i){var e=i=='x'?'Width':'Height',h='scroll'+e;if(!d(a).is('html,body'))return a[h]-d(a)[e.toLowerCase()]();var c='client'+e,l=a.ownerDocument.documentElement,m=a.ownerDocument.body;return Math.max(l[h],m[h])-Math.min(l[c],m[c])};function p(a){return typeof a=='object'?a:{top:a,left:a}}})(jQuery);

// jQuery.mousewheel
(function(d){function e(a){var b=a||window.event,c=[].slice.call(arguments,1),f=0,e=0,g=0,a=d.event.fix(b);a.type="mousewheel";b.wheelDelta&&(f=b.wheelDelta/120);b.detail&&(f=-b.detail/3);g=f;b.axis!==void 0&&b.axis===b.HORIZONTAL_AXIS&&(g=0,e=-1*f);b.wheelDeltaY!==void 0&&(g=b.wheelDeltaY/120);b.wheelDeltaX!==void 0&&(e=-1*b.wheelDeltaX/120);c.unshift(a,f,e,g);return(d.event.dispatch||d.event.handle).apply(this,c)}var c=["DOMMouseScroll","mousewheel"];if(d.event.fixHooks)for(var h=c.length;h;)d.event.fixHooks[c[--h]]=
d.event.mouseHooks;d.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var a=c.length;a;)this.addEventListener(c[--a],e,false);else this.onmousewheel=e},teardown:function(){if(this.removeEventListener)for(var a=c.length;a;)this.removeEventListener(c[--a],e,false);else this.onmousewheel=null}};d.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);

// Placeholder for IE
$.fn.placeholder=function(a){var b={css_class:"placeholder"};var c=$.extend(b,a);var d=document.createElement("input");$.extend($.support,{placeholder:!!("placeholder"in d)});$(this).each(function(){if($.support.placeholder){return false}if($(this).attr("placeholder")!==undefined){var a=$(this).attr("placeholder");var b=$(this).attr("value");$(this).attr("autocomplete","off");if(a===b){$(this).addClass(c.css_class)}if(b===""){$(this).addClass(c.css_class);$(this).val(a)}if($(this).attr("type")==="password"){var d=$(this).attr("placeholder");var e=$("<span />",{text:d,"class":c.css_class,css:{position:"absolute",fontFamily:'"Segoe UI", sans-serif',background:"transparent",cursor:"text",border:"0 none",top:$(this).position().top,left:$(this).position().left,lineHeight:$(this).height()+3+"px",paddingLeft:parseFloat($(this).css("paddingLeft"))+2+"px"}}).insertAfter(this);$(this).val("").addClass(c.css_class);e.click(function(){e.hide();$(this).prev('input[type="password"]').focus().addClass("typing").removeClass("placeholder")});$(this).focusin(function(){if($(this).hasClass(c.css_class)){e.hide();$(this).removeClass(c.css_class)}});$(this).focusout(function(){if($(this).val()===""){e.show();$(this).val("").addClass(c.css_class)}})}if($(this).attr("type")!=="password"){$(this).focusin(function(){var a=$(this).attr("placeholder");if(a===$(this).val()){$(this).val("").removeClass(c.css_class)}});$(this).focusout(function(){var a=$(this).attr("placeholder");$(this).removeClass(c.css_class);if($(this).val()===""&&$(this).val()!==a){$(this).val(a).removeClass(c.css_class)}if($(this).val()===a){$(this).addClass(c.css_class)}})}}$(this).parents("form").submit(function(){$(this).find("[placeholder]").each(function(){var a=$(this);if(a.val()===a.attr("placeholder")){a.val("")}})})})}